// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ow_backendAPI.Data;

#nullable disable

namespace ow_backendAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ow_backendAPI.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_users", "data");
                });

            modelBuilder.Entity("ow_backendAPI.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("hero_list", "data");
                });

            modelBuilder.Entity("ow_backendAPI.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<int>("ModeId")
                        .HasColumnType("integer")
                        .HasColumnName("mode_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("map_list", "data");
                });

            modelBuilder.Entity("ow_backendAPI.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnemyTeamBan1Id")
                        .HasColumnType("integer")
                        .HasColumnName("enemy_team_ban_1_id");

                    b.Property<int>("EnemyTeamBan2Id")
                        .HasColumnType("integer")
                        .HasColumnName("enemy_team_ban_2_id");

                    b.Property<string>("EnemyTeamNotes")
                        .HasColumnType("text")
                        .HasColumnName("enemy_team_notes");

                    b.Property<int>("Hero1Id")
                        .HasColumnType("integer")
                        .HasColumnName("hero_1_id");

                    b.Property<int?>("Hero2Id")
                        .HasColumnType("integer")
                        .HasColumnName("hero_2_id");

                    b.Property<int?>("Hero3Id")
                        .HasColumnType("integer")
                        .HasColumnName("hero_3_id");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<string>("MatchResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_result");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rank");

                    b.Property<int>("RankDivision")
                        .HasColumnType("integer")
                        .HasColumnName("rank_division");

                    b.Property<int>("RankPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("rank_percentage");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<string>("SubmitTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submit_time");

                    b.Property<int>("TeamBan1Id")
                        .HasColumnType("integer")
                        .HasColumnName("team_ban_1_id");

                    b.Property<int>("TeamBan2Id")
                        .HasColumnType("integer")
                        .HasColumnName("team_ban_2_id");

                    b.Property<string>("TeamNotes")
                        .HasColumnType("text")
                        .HasColumnName("team_notes");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EnemyTeamBan1Id");

                    b.HasIndex("EnemyTeamBan2Id");

                    b.HasIndex("Hero1Id");

                    b.HasIndex("Hero2Id");

                    b.HasIndex("Hero3Id");

                    b.HasIndex("MapId");

                    b.HasIndex("TeamBan1Id");

                    b.HasIndex("TeamBan2Id");

                    b.HasIndex("UserId");

                    b.ToTable("game_records", "data");
                });

            modelBuilder.Entity("ow_backendAPI.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("refresh_tokens", "data");
                });

            modelBuilder.Entity("ow_backendAPI.Models.Match", b =>
                {
                    b.HasOne("ow_backendAPI.Models.Hero", "EnemyTeamBan1")
                        .WithMany()
                        .HasForeignKey("EnemyTeamBan1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ow_backendAPI.Models.Hero", "EnemyTeamBan2")
                        .WithMany()
                        .HasForeignKey("EnemyTeamBan2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ow_backendAPI.Models.Hero", "Hero1")
                        .WithMany()
                        .HasForeignKey("Hero1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ow_backendAPI.Models.Hero", "Hero2")
                        .WithMany()
                        .HasForeignKey("Hero2Id");

                    b.HasOne("ow_backendAPI.Models.Hero", "Hero3")
                        .WithMany()
                        .HasForeignKey("Hero3Id");

                    b.HasOne("ow_backendAPI.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ow_backendAPI.Models.Hero", "TeamBan1")
                        .WithMany()
                        .HasForeignKey("TeamBan1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ow_backendAPI.Models.Hero", "TeamBan2")
                        .WithMany()
                        .HasForeignKey("TeamBan2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ow_backendAPI.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyTeamBan1");

                    b.Navigation("EnemyTeamBan2");

                    b.Navigation("Hero1");

                    b.Navigation("Hero2");

                    b.Navigation("Hero3");

                    b.Navigation("Map");

                    b.Navigation("TeamBan1");

                    b.Navigation("TeamBan2");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
