name: Deploy Production to EC2

on:
  workflow_dispatch:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.103
          
      - name: Clean previous deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/ow_backendAPI
            sudo mkdir -p /var/www/ow_backendAPI
            sudo chown $USER:$USER /var/www/ow_backendAPI
        
      - name: Build & Publish
        run: |
          dotnet restore ow_backendAPI/ow_backendAPI.csproj
          dotnet publish ow_backendAPI.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Deploy via SSH
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "ow_backendAPI/publish/**"
          target: "/var/www"

      - name: Update environment variables on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: deploy
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo tee /etc/.production.env > /dev/null <<EOF
            Database__Host=${{ secrets.DB_HOSTNAME }}
            Database__Password=${{ secrets.DB_PASSWORD }}
            Database__Name=${{ secrets.DB_NAME }}
            Database__Username=${{ secrets.DB_USERNAME }}
            ASPNETCORE_ENVIRONMENT=Production
            EOF
            
            sudo chmod 600 /etc/.production.env
            sudo systemctl restart ow_backendAPI